export const CHANGE_INPUT = 'CHANGE_INPUT';
export const LOGIN = 'LOGIN';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const WRONG_AUTHORIZE = 'WRONG_AUTHORIZE';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CORRECT_AUTHORIZE = 'CORRECT_AUTHORIZE';
export const AUTHORIZED = 'AUTHORIZED';