export const CHANGE_INPUT = 'CHANGE_INPUT';
export const LOGIN = 'LOGIN';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const WRONG_AUTHORIZE = 'WRONG_AUTHORIZE';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CORRECT_AUTHORIZE = 'CORRECT_AUTHORIZE';
export const AUTHORIZED = 'AUTHORIZED';

export const CHANGE_INPUT_ADDPRODUCT = 'CHANGE_INPUT_ADDPRODUCT';
export const CLEAN_FORM = 'CLEAN_FORM';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const CHANGE_INPUT_EDITPRODUCT = 'CHANGE_INPUT_EDITPRODUCT';